spring.application.name=minerva-core
spring.profiles.default=sqlite
logging.level.root=DEBUG
logging.level.com.fractalmindstudio.minerva_core=DEBUG
logging.file.name=logs.minerva.log
server.port=${SERVER_PORT:8080}
